// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.ASC.Web.Api.Models
{
    /// <summary>
    /// Password settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PasswordSettingsRequestsDto : IParsable
    {
        /// <summary>Specifies if the password must include the digits or not</summary>
        public bool? Digits { get; set; }
        /// <summary>Minimum password length</summary>
        public int? MinLength { get; set; }
        /// <summary>Specifies if the password must include the special symbols or not</summary>
        public bool? SpecSymbols { get; set; }
        /// <summary>Specifies if the password must include the uppercase letters or not</summary>
        public bool? UpperCase { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.ASC.Web.Api.Models.PasswordSettingsRequestsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.ASC.Web.Api.Models.PasswordSettingsRequestsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.ASC.Web.Api.Models.PasswordSettingsRequestsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "digits", n => { Digits = n.GetBoolValue(); } },
                { "minLength", n => { MinLength = n.GetIntValue(); } },
                { "specSymbols", n => { SpecSymbols = n.GetBoolValue(); } },
                { "upperCase", n => { UpperCase = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("digits", Digits);
            writer.WriteIntValue("minLength", MinLength);
            writer.WriteBoolValue("specSymbols", SpecSymbols);
            writer.WriteBoolValue("upperCase", UpperCase);
        }
    }
}
#pragma warning restore CS0618
