// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.TwoZero.People.Activationstatus
{
    /// <summary>
    /// Builds and executes requests for operations under \api\2.0\people\activationstatus
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivationstatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaPosts.Client.api.TwoZero.people.activationstatus.item collection</summary>
        /// <param name="position">Activation status</param>
        /// <returns>A <see cref="global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item.WithActivationstatusItemRequestBuilder"/></returns>
        public global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item.WithActivationstatusItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("activationstatus", position);
                return new global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item.WithActivationstatusItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the KiotaPosts.Client.api.TwoZero.people.activationstatus.item collection</summary>
        /// <param name="position">Activation status</param>
        /// <returns>A <see cref="global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item.WithActivationstatusItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item.WithActivationstatusItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("activationstatus", position);
                return new global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.Item.WithActivationstatusItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.ActivationstatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivationstatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/2.0/people/activationstatus", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Api.TwoZero.People.Activationstatus.ActivationstatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivationstatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/2.0/people/activationstatus", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
