/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// The auto-clearing setting parameters.
    /// </summary>
    [DataContract(Name = "AutoCleanUpData")]
    public partial class AutoCleanUpData : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Gap
        /// </summary>
        [DataMember(Name = "gap", EmitDefaultValue = false)]
        public DateToAutoCleanUp? Gap { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoCleanUpData" /> class.
        /// </summary>
        /// <param name="isAutoCleanUp">Specifies whether to permanently delete files in the Trash folder..</param>
        /// <param name="gap">gap.</param>
        public AutoCleanUpData(bool isAutoCleanUp = default(bool), DateToAutoCleanUp? gap = default(DateToAutoCleanUp?))
        {
            this.IsAutoCleanUp = isAutoCleanUp;
            this.Gap = gap;
        }

        /// <summary>
        /// Specifies whether to permanently delete files in the Trash folder.
        /// </summary>
        /// <value>Specifies whether to permanently delete files in the Trash folder.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isAutoCleanUp", EmitDefaultValue = true)]
        public bool IsAutoCleanUp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutoCleanUpData {\n");
            sb.Append("  IsAutoCleanUp: ").Append(IsAutoCleanUp).Append("\n");
            sb.Append("  Gap: ").Append(Gap).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
