/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// Cookies settings request parameters
    /// </summary>
    [DataContract(Name = "CookieSettingsRequestsDto")]
    public partial class CookieSettingsRequestsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CookieSettingsRequestsDto" /> class.
        /// </summary>
        /// <param name="lifeTime">Lifetime value in minutes.</param>
        /// <param name="enabled">Specifies if the cookie settings are enabled or not.</param>
        public CookieSettingsRequestsDto(int lifeTime = default(int), bool enabled = default(bool))
        {
            this.LifeTime = lifeTime;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Lifetime value in minutes
        /// </summary>
        /// <value>Lifetime value in minutes</value>
        /*
        <example>1234</example>
        */
        [DataMember(Name = "lifeTime", EmitDefaultValue = false)]
        public int LifeTime { get; set; }

        /// <summary>
        /// Specifies if the cookie settings are enabled or not
        /// </summary>
        /// <value>Specifies if the cookie settings are enabled or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CookieSettingsRequestsDto {\n");
            sb.Append("  LifeTime: ").Append(LifeTime).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
