/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// The currencies parameters.
    /// </summary>
    [DataContract(Name = "CurrenciesDto")]
    public partial class CurrenciesDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrenciesDto" /> class.
        /// </summary>
        /// <param name="isoCountryCode">The ISO country code..</param>
        /// <param name="isoCurrencySymbol">The ISO currency symbol..</param>
        /// <param name="currencyNativeName">The currency native name..</param>
        public CurrenciesDto(string isoCountryCode = default(string), string isoCurrencySymbol = default(string), string currencyNativeName = default(string))
        {
            this.IsoCountryCode = isoCountryCode;
            this.IsoCurrencySymbol = isoCurrencySymbol;
            this.CurrencyNativeName = currencyNativeName;
        }

        /// <summary>
        /// The ISO country code.
        /// </summary>
        /// <value>The ISO country code.</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "isoCountryCode", EmitDefaultValue = true)]
        public string IsoCountryCode { get; set; }

        /// <summary>
        /// The ISO currency symbol.
        /// </summary>
        /// <value>The ISO currency symbol.</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "isoCurrencySymbol", EmitDefaultValue = true)]
        public string IsoCurrencySymbol { get; set; }

        /// <summary>
        /// The currency native name.
        /// </summary>
        /// <value>The currency native name.</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "currencyNativeName", EmitDefaultValue = true)]
        public string CurrencyNativeName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CurrenciesDto {\n");
            sb.Append("  IsoCountryCode: ").Append(IsoCountryCode).Append("\n");
            sb.Append("  IsoCurrencySymbol: ").Append(IsoCurrencySymbol).Append("\n");
            sb.Append("  CurrencyNativeName: ").Append(CurrencyNativeName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
