/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// The theme type.
    /// </summary>
    /// <value>The theme type.</value>
    public enum DarkThemeSettingsType
    {
        /// <summary>
        /// Enum Base for value: 0
        /// </summary>
        Base = 0,

        /// <summary>
        /// Enum Dark for value: 1
        /// </summary>
        Dark = 1,

        /// <summary>
        /// Enum System for value: 2
        /// </summary>
        System = 2
    }

}
