/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// Confirmation email parameters
    /// </summary>
    [DataContract(Name = "EmailValidationKeyModel")]
    public partial class EmailValidationKeyModel : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets EmplType
        /// </summary>
        [DataMember(Name = "emplType", EmitDefaultValue = false)]
        public EmployeeType? EmplType { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public ConfirmType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailValidationKeyModel" /> class.
        /// </summary>
        /// <param name="key">Key.</param>
        /// <param name="emplType">emplType.</param>
        /// <param name="email">Email.</param>
        /// <param name="uiD">User ID.</param>
        /// <param name="type">type.</param>
        /// <param name="first">Access an account for the first time or not.</param>
        /// <param name="roomId">Room ID.</param>
        public EmailValidationKeyModel(string key = default(string), EmployeeType? emplType = default(EmployeeType?), string email = default(string), Guid? uiD = default(Guid?), ConfirmType? type = default(ConfirmType?), string first = default(string), string roomId = default(string))
        {
            this.Key = key;
            this.EmplType = emplType;
            this.Email = email;
            this.UiD = uiD;
            this.Type = type;
            this.First = first;
            this.RoomId = roomId;
        }

        /// <summary>
        /// Key
        /// </summary>
        /// <value>Key</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "key", EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        /// <value>Email</value>
        /*
        <example>Sydney_Roberts4@hotmail.com</example>
        */
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// User ID
        /// </summary>
        /// <value>User ID</value>
        /*
        <example>75a5f745-f697-4418-b38d-0fe0d277e258</example>
        */
        [DataMember(Name = "uiD", EmitDefaultValue = true)]
        public Guid? UiD { get; set; }

        /// <summary>
        /// Access an account for the first time or not
        /// </summary>
        /// <value>Access an account for the first time or not</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "first", EmitDefaultValue = true)]
        public string First { get; set; }

        /// <summary>
        /// Room ID
        /// </summary>
        /// <value>Room ID</value>
        /*
        <example>9846</example>
        */
        [DataMember(Name = "roomId", EmitDefaultValue = true)]
        public string RoomId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailValidationKeyModel {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  EmplType: ").Append(EmplType).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  UiD: ").Append(UiD).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  First: ").Append(First).Append("\n");
            sb.Append("  RoomId: ").Append(RoomId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
