/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// EmployeeFullDto
    /// </summary>
    [DataContract(Name = "EmployeeFullDto")]
    public partial class EmployeeFullDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public EmployeeStatus? Status { get; set; }

        /// <summary>
        /// Gets or Sets ActivationStatus
        /// </summary>
        [DataMember(Name = "activationStatus", EmitDefaultValue = false)]
        public EmployeeActivationStatus? ActivationStatus { get; set; }

        /// <summary>
        /// Gets or Sets MobilePhoneActivationStatus
        /// </summary>
        [DataMember(Name = "mobilePhoneActivationStatus", EmitDefaultValue = false)]
        public MobilePhoneActivationStatus? MobilePhoneActivationStatus { get; set; }

        /// <summary>
        /// Gets or Sets Theme
        /// </summary>
        [DataMember(Name = "theme", EmitDefaultValue = false)]
        public DarkThemeSettingsType? Theme { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeeFullDto" /> class.
        /// </summary>
        /// <param name="id">ID.</param>
        /// <param name="displayName">Display name.</param>
        /// <param name="title">Title.</param>
        /// <param name="avatar">Avatar.</param>
        /// <param name="avatarOriginal">Original size avatar.</param>
        /// <param name="avatarMax">Maximum size avatar.</param>
        /// <param name="avatarMedium">Medium size avatar.</param>
        /// <param name="avatarSmall">Small avatar.</param>
        /// <param name="profileUrl">Profile URL.</param>
        /// <param name="hasAvatar">Specifies if the user has an avatar or not.</param>
        /// <param name="isAnonim">Specifies if the user is an anonim or not.</param>
        /// <param name="firstName">First name.</param>
        /// <param name="lastName">Last name.</param>
        /// <param name="userName">Username.</param>
        /// <param name="email">Email.</param>
        /// <param name="contacts">List of contacts.</param>
        /// <param name="birthday">birthday.</param>
        /// <param name="sex">Sex.</param>
        /// <param name="status">status.</param>
        /// <param name="activationStatus">activationStatus.</param>
        /// <param name="terminated">terminated.</param>
        /// <param name="department">Department.</param>
        /// <param name="workFrom">workFrom.</param>
        /// <param name="groups">List of groups.</param>
        /// <param name="location">Location.</param>
        /// <param name="notes">Notes.</param>
        /// <param name="isAdmin">Specifies if the user is an administrator or not.</param>
        /// <param name="isRoomAdmin">Specifies if the user is a room administrator or not.</param>
        /// <param name="isLDAP">Specifies if the LDAP settings are enabled for the user or not.</param>
        /// <param name="listAdminModules">List of administrator modules.</param>
        /// <param name="isOwner">Specifies if the user is a portal owner or not.</param>
        /// <param name="isVisitor">Specifies if the user is a portal visitor or not.</param>
        /// <param name="isCollaborator">Specifies if the user is a portal collaborator or not.</param>
        /// <param name="cultureName">Language.</param>
        /// <param name="mobilePhone">Mobile phone number.</param>
        /// <param name="mobilePhoneActivationStatus">mobilePhoneActivationStatus.</param>
        /// <param name="isSSO">Specifies if the SSO settings are enabled for the user or not.</param>
        /// <param name="theme">theme.</param>
        /// <param name="quotaLimit">Quota limit.</param>
        /// <param name="usedSpace">Portal used space.</param>
        /// <param name="shared">Shared.</param>
        /// <param name="isCustomQuota">Specifies if the user has a custom quota or not.</param>
        /// <param name="loginEventId">Current login event ID.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="registrationDate">registrationDate.</param>
        public EmployeeFullDto(Guid id = default(Guid), string displayName = default(string), string title = default(string), string avatar = default(string), string avatarOriginal = default(string), string avatarMax = default(string), string avatarMedium = default(string), string avatarSmall = default(string), string profileUrl = default(string), bool hasAvatar = default(bool), bool isAnonim = default(bool), string firstName = default(string), string lastName = default(string), string userName = default(string), string email = default(string), List<Contact> contacts = default(List<Contact>), ApiDateTime birthday = default(ApiDateTime), string sex = default(string), EmployeeStatus? status = default(EmployeeStatus?), EmployeeActivationStatus? activationStatus = default(EmployeeActivationStatus?), ApiDateTime terminated = default(ApiDateTime), string department = default(string), ApiDateTime workFrom = default(ApiDateTime), List<GroupSummaryDto> groups = default(List<GroupSummaryDto>), string location = default(string), string notes = default(string), bool isAdmin = default(bool), bool isRoomAdmin = default(bool), bool isLDAP = default(bool), List<string> listAdminModules = default(List<string>), bool isOwner = default(bool), bool isVisitor = default(bool), bool isCollaborator = default(bool), string cultureName = default(string), string mobilePhone = default(string), MobilePhoneActivationStatus? mobilePhoneActivationStatus = default(MobilePhoneActivationStatus?), bool isSSO = default(bool), DarkThemeSettingsType? theme = default(DarkThemeSettingsType?), long? quotaLimit = default(long?), double? usedSpace = default(double?), bool? shared = default(bool?), bool? isCustomQuota = default(bool?), int? loginEventId = default(int?), EmployeeDto createdBy = default(EmployeeDto), ApiDateTime registrationDate = default(ApiDateTime))
        {
            this.Id = id;
            this.DisplayName = displayName;
            this.Title = title;
            this.Avatar = avatar;
            this.AvatarOriginal = avatarOriginal;
            this.AvatarMax = avatarMax;
            this.AvatarMedium = avatarMedium;
            this.AvatarSmall = avatarSmall;
            this.ProfileUrl = profileUrl;
            this.HasAvatar = hasAvatar;
            this.IsAnonim = isAnonim;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.UserName = userName;
            this.Email = email;
            this.Contacts = contacts;
            this.Birthday = birthday;
            this.Sex = sex;
            this.Status = status;
            this.ActivationStatus = activationStatus;
            this.Terminated = terminated;
            this.Department = department;
            this.WorkFrom = workFrom;
            this.Groups = groups;
            this.Location = location;
            this.Notes = notes;
            this.IsAdmin = isAdmin;
            this.IsRoomAdmin = isRoomAdmin;
            this.IsLDAP = isLDAP;
            this.ListAdminModules = listAdminModules;
            this.IsOwner = isOwner;
            this.IsVisitor = isVisitor;
            this.IsCollaborator = isCollaborator;
            this.CultureName = cultureName;
            this.MobilePhone = mobilePhone;
            this.MobilePhoneActivationStatus = mobilePhoneActivationStatus;
            this.IsSSO = isSSO;
            this.Theme = theme;
            this.QuotaLimit = quotaLimit;
            this.UsedSpace = usedSpace;
            this.Shared = shared;
            this.IsCustomQuota = isCustomQuota;
            this.LoginEventId = loginEventId;
            this.CreatedBy = createdBy;
            this.RegistrationDate = registrationDate;
        }

        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Display name
        /// </summary>
        /// <value>Display name</value>
        /*
        <example>Mike Zanyatski</example>
        */
        [DataMember(Name = "displayName", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Title
        /// </summary>
        /// <value>Title</value>
        /*
        <example>Manager</example>
        */
        [DataMember(Name = "title", EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Avatar
        /// </summary>
        /// <value>Avatar</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "avatar", EmitDefaultValue = true)]
        public string Avatar { get; set; }

        /// <summary>
        /// Original size avatar
        /// </summary>
        /// <value>Original size avatar</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "avatarOriginal", EmitDefaultValue = true)]
        public string AvatarOriginal { get; set; }

        /// <summary>
        /// Maximum size avatar
        /// </summary>
        /// <value>Maximum size avatar</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "avatarMax", EmitDefaultValue = true)]
        public string AvatarMax { get; set; }

        /// <summary>
        /// Medium size avatar
        /// </summary>
        /// <value>Medium size avatar</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "avatarMedium", EmitDefaultValue = true)]
        public string AvatarMedium { get; set; }

        /// <summary>
        /// Small avatar
        /// </summary>
        /// <value>Small avatar</value>
        /*
        <example>url to small avatar</example>
        */
        [DataMember(Name = "avatarSmall", EmitDefaultValue = true)]
        public string AvatarSmall { get; set; }

        /// <summary>
        /// Profile URL
        /// </summary>
        /// <value>Profile URL</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "profileUrl", EmitDefaultValue = true)]
        public string ProfileUrl { get; set; }

        /// <summary>
        /// Specifies if the user has an avatar or not
        /// </summary>
        /// <value>Specifies if the user has an avatar or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "hasAvatar", EmitDefaultValue = true)]
        public bool HasAvatar { get; set; }

        /// <summary>
        /// Specifies if the user is an anonim or not
        /// </summary>
        /// <value>Specifies if the user is an anonim or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isAnonim", EmitDefaultValue = true)]
        public bool IsAnonim { get; set; }

        /// <summary>
        /// First name
        /// </summary>
        /// <value>First name</value>
        /*
        <example>Mike</example>
        */
        [DataMember(Name = "firstName", EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Last name
        /// </summary>
        /// <value>Last name</value>
        /*
        <example>Zanyatski</example>
        */
        [DataMember(Name = "lastName", EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Username
        /// </summary>
        /// <value>Username</value>
        /*
        <example>Mike.Zanyatski</example>
        */
        [DataMember(Name = "userName", EmitDefaultValue = true)]
        public string UserName { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        /// <value>Email</value>
        /*
        <example>my@gmail.com</example>
        */
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// List of contacts
        /// </summary>
        /// <value>List of contacts</value>
        [DataMember(Name = "contacts", EmitDefaultValue = true)]
        public List<Contact> Contacts { get; set; }

        /// <summary>
        /// Gets or Sets Birthday
        /// </summary>
        [DataMember(Name = "birthday", EmitDefaultValue = false)]
        public ApiDateTime Birthday { get; set; }

        /// <summary>
        /// Sex
        /// </summary>
        /// <value>Sex</value>
        /*
        <example>male</example>
        */
        [DataMember(Name = "sex", EmitDefaultValue = true)]
        public string Sex { get; set; }

        /// <summary>
        /// Gets or Sets Terminated
        /// </summary>
        [DataMember(Name = "terminated", EmitDefaultValue = false)]
        public ApiDateTime Terminated { get; set; }

        /// <summary>
        /// Department
        /// </summary>
        /// <value>Department</value>
        /*
        <example>Marketing</example>
        */
        [DataMember(Name = "department", EmitDefaultValue = true)]
        public string Department { get; set; }

        /// <summary>
        /// Gets or Sets WorkFrom
        /// </summary>
        [DataMember(Name = "workFrom", EmitDefaultValue = false)]
        public ApiDateTime WorkFrom { get; set; }

        /// <summary>
        /// List of groups
        /// </summary>
        /// <value>List of groups</value>
        [DataMember(Name = "groups", EmitDefaultValue = true)]
        public List<GroupSummaryDto> Groups { get; set; }

        /// <summary>
        /// Location
        /// </summary>
        /// <value>Location</value>
        /*
        <example>Palo Alto</example>
        */
        [DataMember(Name = "location", EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Notes
        /// </summary>
        /// <value>Notes</value>
        /*
        <example>Notes to worker</example>
        */
        [DataMember(Name = "notes", EmitDefaultValue = true)]
        public string Notes { get; set; }

        /// <summary>
        /// Specifies if the user is an administrator or not
        /// </summary>
        /// <value>Specifies if the user is an administrator or not</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isAdmin", EmitDefaultValue = true)]
        public bool IsAdmin { get; set; }

        /// <summary>
        /// Specifies if the user is a room administrator or not
        /// </summary>
        /// <value>Specifies if the user is a room administrator or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isRoomAdmin", EmitDefaultValue = true)]
        public bool IsRoomAdmin { get; set; }

        /// <summary>
        /// Specifies if the LDAP settings are enabled for the user or not
        /// </summary>
        /// <value>Specifies if the LDAP settings are enabled for the user or not</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isLDAP", EmitDefaultValue = true)]
        public bool IsLDAP { get; set; }

        /// <summary>
        /// List of administrator modules
        /// </summary>
        /// <value>List of administrator modules</value>
        /*
        <example>[&quot;projects&quot;, &quot;crm&quot;]</example>
        */
        [DataMember(Name = "listAdminModules", EmitDefaultValue = true)]
        public List<string> ListAdminModules { get; set; }

        /// <summary>
        /// Specifies if the user is a portal owner or not
        /// </summary>
        /// <value>Specifies if the user is a portal owner or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isOwner", EmitDefaultValue = true)]
        public bool IsOwner { get; set; }

        /// <summary>
        /// Specifies if the user is a portal visitor or not
        /// </summary>
        /// <value>Specifies if the user is a portal visitor or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isVisitor", EmitDefaultValue = true)]
        public bool IsVisitor { get; set; }

        /// <summary>
        /// Specifies if the user is a portal collaborator or not
        /// </summary>
        /// <value>Specifies if the user is a portal collaborator or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isCollaborator", EmitDefaultValue = true)]
        public bool IsCollaborator { get; set; }

        /// <summary>
        /// Language
        /// </summary>
        /// <value>Language</value>
        /*
        <example>en-EN</example>
        */
        [DataMember(Name = "cultureName", EmitDefaultValue = true)]
        public string CultureName { get; set; }

        /// <summary>
        /// Mobile phone number
        /// </summary>
        /// <value>Mobile phone number</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "mobilePhone", EmitDefaultValue = true)]
        public string MobilePhone { get; set; }

        /// <summary>
        /// Specifies if the SSO settings are enabled for the user or not
        /// </summary>
        /// <value>Specifies if the SSO settings are enabled for the user or not</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isSSO", EmitDefaultValue = true)]
        public bool IsSSO { get; set; }

        /// <summary>
        /// Quota limit
        /// </summary>
        /// <value>Quota limit</value>
        /*
        <example>1234</example>
        */
        [DataMember(Name = "quotaLimit", EmitDefaultValue = true)]
        public long? QuotaLimit { get; set; }

        /// <summary>
        /// Portal used space
        /// </summary>
        /// <value>Portal used space</value>
        /*
        <example>12345</example>
        */
        [DataMember(Name = "usedSpace", EmitDefaultValue = true)]
        public double? UsedSpace { get; set; }

        /// <summary>
        /// Shared
        /// </summary>
        /// <value>Shared</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "shared", EmitDefaultValue = true)]
        public bool? Shared { get; set; }

        /// <summary>
        /// Specifies if the user has a custom quota or not
        /// </summary>
        /// <value>Specifies if the user has a custom quota or not</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isCustomQuota", EmitDefaultValue = true)]
        public bool? IsCustomQuota { get; set; }

        /// <summary>
        /// Current login event ID
        /// </summary>
        /// <value>Current login event ID</value>
        /*
        <example>1234</example>
        */
        [DataMember(Name = "loginEventId", EmitDefaultValue = true)]
        public int? LoginEventId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public EmployeeDto CreatedBy { get; set; }

        /// <summary>
        /// Gets or Sets RegistrationDate
        /// </summary>
        [DataMember(Name = "registrationDate", EmitDefaultValue = false)]
        public ApiDateTime RegistrationDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmployeeFullDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  AvatarOriginal: ").Append(AvatarOriginal).Append("\n");
            sb.Append("  AvatarMax: ").Append(AvatarMax).Append("\n");
            sb.Append("  AvatarMedium: ").Append(AvatarMedium).Append("\n");
            sb.Append("  AvatarSmall: ").Append(AvatarSmall).Append("\n");
            sb.Append("  ProfileUrl: ").Append(ProfileUrl).Append("\n");
            sb.Append("  HasAvatar: ").Append(HasAvatar).Append("\n");
            sb.Append("  IsAnonim: ").Append(IsAnonim).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Contacts: ").Append(Contacts).Append("\n");
            sb.Append("  Birthday: ").Append(Birthday).Append("\n");
            sb.Append("  Sex: ").Append(Sex).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ActivationStatus: ").Append(ActivationStatus).Append("\n");
            sb.Append("  Terminated: ").Append(Terminated).Append("\n");
            sb.Append("  Department: ").Append(Department).Append("\n");
            sb.Append("  WorkFrom: ").Append(WorkFrom).Append("\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  IsAdmin: ").Append(IsAdmin).Append("\n");
            sb.Append("  IsRoomAdmin: ").Append(IsRoomAdmin).Append("\n");
            sb.Append("  IsLDAP: ").Append(IsLDAP).Append("\n");
            sb.Append("  ListAdminModules: ").Append(ListAdminModules).Append("\n");
            sb.Append("  IsOwner: ").Append(IsOwner).Append("\n");
            sb.Append("  IsVisitor: ").Append(IsVisitor).Append("\n");
            sb.Append("  IsCollaborator: ").Append(IsCollaborator).Append("\n");
            sb.Append("  CultureName: ").Append(CultureName).Append("\n");
            sb.Append("  MobilePhone: ").Append(MobilePhone).Append("\n");
            sb.Append("  MobilePhoneActivationStatus: ").Append(MobilePhoneActivationStatus).Append("\n");
            sb.Append("  IsSSO: ").Append(IsSSO).Append("\n");
            sb.Append("  Theme: ").Append(Theme).Append("\n");
            sb.Append("  QuotaLimit: ").Append(QuotaLimit).Append("\n");
            sb.Append("  UsedSpace: ").Append(UsedSpace).Append("\n");
            sb.Append("  Shared: ").Append(Shared).Append("\n");
            sb.Append("  IsCustomQuota: ").Append(IsCustomQuota).Append("\n");
            sb.Append("  LoginEventId: ").Append(LoginEventId).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  RegistrationDate: ").Append(RegistrationDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
