/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// The file statistics result parameters.
    /// </summary>
    [DataContract(Name = "FilesStatisticsResultDto")]
    public partial class FilesStatisticsResultDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilesStatisticsResultDto" /> class.
        /// </summary>
        /// <param name="myDocumentsUsedSpace">myDocumentsUsedSpace.</param>
        /// <param name="trashUsedSpace">trashUsedSpace.</param>
        /// <param name="archiveUsedSpace">archiveUsedSpace.</param>
        /// <param name="roomsUsedSpace">roomsUsedSpace.</param>
        public FilesStatisticsResultDto(FilesStatisticsFolder myDocumentsUsedSpace = default(FilesStatisticsFolder), FilesStatisticsFolder trashUsedSpace = default(FilesStatisticsFolder), FilesStatisticsFolder archiveUsedSpace = default(FilesStatisticsFolder), FilesStatisticsFolder roomsUsedSpace = default(FilesStatisticsFolder))
        {
            this.MyDocumentsUsedSpace = myDocumentsUsedSpace;
            this.TrashUsedSpace = trashUsedSpace;
            this.ArchiveUsedSpace = archiveUsedSpace;
            this.RoomsUsedSpace = roomsUsedSpace;
        }

        /// <summary>
        /// Gets or Sets MyDocumentsUsedSpace
        /// </summary>
        [DataMember(Name = "myDocumentsUsedSpace", EmitDefaultValue = false)]
        public FilesStatisticsFolder MyDocumentsUsedSpace { get; set; }

        /// <summary>
        /// Gets or Sets TrashUsedSpace
        /// </summary>
        [DataMember(Name = "trashUsedSpace", EmitDefaultValue = false)]
        public FilesStatisticsFolder TrashUsedSpace { get; set; }

        /// <summary>
        /// Gets or Sets ArchiveUsedSpace
        /// </summary>
        [DataMember(Name = "archiveUsedSpace", EmitDefaultValue = false)]
        public FilesStatisticsFolder ArchiveUsedSpace { get; set; }

        /// <summary>
        /// Gets or Sets RoomsUsedSpace
        /// </summary>
        [DataMember(Name = "roomsUsedSpace", EmitDefaultValue = false)]
        public FilesStatisticsFolder RoomsUsedSpace { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilesStatisticsResultDto {\n");
            sb.Append("  MyDocumentsUsedSpace: ").Append(MyDocumentsUsedSpace).Append("\n");
            sb.Append("  TrashUsedSpace: ").Append(TrashUsedSpace).Append("\n");
            sb.Append("  ArchiveUsedSpace: ").Append(ArchiveUsedSpace).Append("\n");
            sb.Append("  RoomsUsedSpace: ").Append(RoomsUsedSpace).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
