/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// The parameters for saving the file as PDF.
    /// </summary>
    [DataContract(Name = "SaveAsPdfInteger")]
    public partial class SaveAsPdfInteger : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveAsPdfInteger" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SaveAsPdfInteger() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveAsPdfInteger" /> class.
        /// </summary>
        /// <param name="folderId">The folder ID to save the file as PDF. (required).</param>
        /// <param name="title">The file title to save as PDF. (required).</param>
        public SaveAsPdfInteger(int folderId = default(int), string title = default(string))
        {
            this.FolderId = folderId;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for SaveAsPdfInteger and cannot be null");
            }
            this.Title = title;
        }

        /// <summary>
        /// The folder ID to save the file as PDF.
        /// </summary>
        /// <value>The folder ID to save the file as PDF.</value>
        /*
        <example>9846</example>
        */
        [DataMember(Name = "folderId", IsRequired = true, EmitDefaultValue = true)]
        public int FolderId { get; set; }

        /// <summary>
        /// The file title to save as PDF.
        /// </summary>
        /// <value>The file title to save as PDF.</value>
        /*
        <example>legacy_1080p_small_wooden_mouse</example>
        */
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SaveAsPdfInteger {\n");
            sb.Append("  FolderId: ").Append(FolderId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
