/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// Storage settings request parameters
    /// </summary>
    [DataContract(Name = "StorageRequestsDto")]
    public partial class StorageRequestsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageRequestsDto" /> class.
        /// </summary>
        /// <param name="module">Storage name.</param>
        /// <param name="props">Storage properties.</param>
        public StorageRequestsDto(string module = default(string), List<ItemKeyValuePairStringString> props = default(List<ItemKeyValuePairStringString>))
        {
            this.Module = module;
            this.Props = props;
        }

        /// <summary>
        /// Storage name
        /// </summary>
        /// <value>Storage name</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "module", EmitDefaultValue = true)]
        public string Module { get; set; }

        /// <summary>
        /// Storage properties
        /// </summary>
        /// <value>Storage properties</value>
        [DataMember(Name = "props", EmitDefaultValue = true)]
        public List<ItemKeyValuePairStringString> Props { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageRequestsDto {\n");
            sb.Append("  Module: ").Append(Module).Append("\n");
            sb.Append("  Props: ").Append(Props).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
