/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Docspace.Client.FileParameter;
using OpenAPIDateConverter = Docspace.Client.OpenAPIDateConverter;

namespace Docspace.Model
{
    /// <summary>
    /// The domain validator.
    /// </summary>
    [DataContract(Name = "TenantDomainValidator")]
    public partial class TenantDomainValidator : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantDomainValidator" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public TenantDomainValidator()
        {
        }

        /// <summary>
        /// The regex string to validate a domain.
        /// </summary>
        /// <value>The regex string to validate a domain.</value>
        /*
        <example>some text</example>
        */
        [DataMember(Name = "regex", EmitDefaultValue = true)]
        public string Regex { get; private set; }

        /// <summary>
        /// Returns false as Regex should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRegex()
        {
            return false;
        }
        /// <summary>
        /// The minimum length of the valid domain.
        /// </summary>
        /// <value>The minimum length of the valid domain.</value>
        /*
        <example>1234</example>
        */
        [DataMember(Name = "minLength", EmitDefaultValue = false)]
        public int MinLength { get; private set; }

        /// <summary>
        /// Returns false as MinLength should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMinLength()
        {
            return false;
        }
        /// <summary>
        /// The maximum length of the valid domain.
        /// </summary>
        /// <value>The maximum length of the valid domain.</value>
        /*
        <example>63</example>
        */
        [DataMember(Name = "maxLength", EmitDefaultValue = false)]
        public int MaxLength { get; private set; }

        /// <summary>
        /// Returns false as MaxLength should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMaxLength()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantDomainValidator {\n");
            sb.Append("  Regex: ").Append(Regex).Append("\n");
            sb.Append("  MinLength: ").Append(MinLength).Append("\n");
            sb.Append("  MaxLength: ").Append(MaxLength).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
