/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Docspace.Client;
using Docspace.Api;
// uncomment below to import models
//using Docspace.Model;

namespace Docspace.Test.Api
{
    /// <summary>
    ///  Class for testing SettingsWebhooksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SettingsWebhooksApiTests : IDisposable
    {
        private SettingsWebhooksApi instance;

        public SettingsWebhooksApiTests()
        {
            instance = new SettingsWebhooksApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettingsWebhooksApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SettingsWebhooksApi
            //Assert.IsType<SettingsWebhooksApi>(instance);
        }

        /// <summary>
        /// Test CreateWebhook
        /// </summary>
        [Fact]
        public void CreateWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebhooksConfigRequestsDto? webhooksConfigRequestsDto = null;
            //var response = instance.CreateWebhook(webhooksConfigRequestsDto);
            //Assert.IsType<WebhooksConfigWrapper>(response);
        }

        /// <summary>
        /// Test DisableWebHook
        /// </summary>
        [Fact]
        public void DisableWebHookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.DisableWebHook(id);
            //Assert.IsType<WebhookWrapper>(response);
        }

        /// <summary>
        /// Test GetJournal
        /// </summary>
        [Fact]
        public void GetJournalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? deliveryFrom = null;
            //DateTime? deliveryTo = null;
            //string? hookUri = null;
            //int? webhookId = null;
            //int? configId = null;
            //int? eventId = null;
            //WebhookGroupStatus? groupStatus = null;
            //var response = instance.GetJournal(deliveryFrom, deliveryTo, hookUri, webhookId, configId, eventId, groupStatus);
            //Assert.IsType<WebhooksLogArrayWrapper>(response);
        }

        /// <summary>
        /// Test GetTenantWebhooks
        /// </summary>
        [Fact]
        public void GetTenantWebhooksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetTenantWebhooks();
            //Assert.IsType<WebhooksConfigWithStatusArrayWrapper>(response);
        }

        /// <summary>
        /// Test RemoveWebhook
        /// </summary>
        [Fact]
        public void RemoveWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.RemoveWebhook(id);
            //Assert.IsType<WebhooksConfigWrapper>(response);
        }

        /// <summary>
        /// Test RetryWebhook
        /// </summary>
        [Fact]
        public void RetryWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.RetryWebhook(id);
            //Assert.IsType<WebhooksLogWrapper>(response);
        }

        /// <summary>
        /// Test RetryWebhooks
        /// </summary>
        [Fact]
        public void RetryWebhooksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebhookRetryRequestsDto? webhookRetryRequestsDto = null;
            //var response = instance.RetryWebhooks(webhookRetryRequestsDto);
            //Assert.IsType<WebhooksLogArrayWrapper>(response);
        }

        /// <summary>
        /// Test Settings
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Settings();
            //Assert.IsType<WebhookArrayWrapper>(response);
        }

        /// <summary>
        /// Test UpdateWebhook
        /// </summary>
        [Fact]
        public void UpdateWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WebhooksConfigRequestsDto? webhooksConfigRequestsDto = null;
            //var response = instance.UpdateWebhook(webhooksConfigRequestsDto);
            //Assert.IsType<WebhooksConfigWrapper>(response);
        }
    }
}
