// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Api.TwoZero.People.Reassign.Progress;
using KiotaPosts.Client.Api.TwoZero.People.Reassign.Start;
using KiotaPosts.Client.Api.TwoZero.People.Reassign.Terminate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.TwoZero.People.Reassign
{
    /// <summary>
    /// Builds and executes requests for operations under \api\2.0\people\reassign
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReassignRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The progress property</summary>
        public global::KiotaPosts.Client.Api.TwoZero.People.Reassign.Progress.ProgressRequestBuilder Progress
        {
            get => new global::KiotaPosts.Client.Api.TwoZero.People.Reassign.Progress.ProgressRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::KiotaPosts.Client.Api.TwoZero.People.Reassign.Start.StartRequestBuilder Start
        {
            get => new global::KiotaPosts.Client.Api.TwoZero.People.Reassign.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminate property</summary>
        public global::KiotaPosts.Client.Api.TwoZero.People.Reassign.Terminate.TerminateRequestBuilder Terminate
        {
            get => new global::KiotaPosts.Client.Api.TwoZero.People.Reassign.Terminate.TerminateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Api.TwoZero.People.Reassign.ReassignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReassignRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/2.0/people/reassign", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Api.TwoZero.People.Reassign.ReassignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReassignRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/2.0/people/reassign", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
