name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build "./src/DocSpace.API.SDK/" --configuration Release --no-restore
      
      - name: Pack NuGet package
        run: dotnet pack "./src/DocSpace.API.SDK/" --configuration Release --no-build --output ./nupkg

      - name: Generate Changelog
        run: |
          awk '/## [0-9]/{p++} p; /## [0-9]/{if (p > 1) exit}' CHANGELOG.md | awk 'NR>2 {print last} {last=$0}' > RELEASE.md

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: RELEASE.md
          tag: ${{ github.ref_name }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
