/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing AdminMessageSettingsRequestsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminMessageSettingsRequestsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminMessageSettingsRequestsDto
        //private AdminMessageSettingsRequestsDto instance;

        public AdminMessageSettingsRequestsDtoTests()
        {
            // TODO uncomment below to create an instance of AdminMessageSettingsRequestsDto
            //instance = new AdminMessageSettingsRequestsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminMessageSettingsRequestsDto
        /// </summary>
        [Fact]
        public void AdminMessageSettingsRequestsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminMessageSettingsRequestsDto
            //Assert.IsType<AdminMessageSettingsRequestsDto>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Culture'
        /// </summary>
        [Fact]
        public void CultureTest()
        {
            // TODO unit test for the property 'Culture'
        }
    }
}
