/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing ArchiveRoomRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArchiveRoomRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArchiveRoomRequest
        //private ArchiveRoomRequest instance;

        public ArchiveRoomRequestTests()
        {
            // TODO uncomment below to create an instance of ArchiveRoomRequest
            //instance = new ArchiveRoomRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArchiveRoomRequest
        /// </summary>
        [Fact]
        public void ArchiveRoomRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArchiveRoomRequest
            //Assert.IsType<ArchiveRoomRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DeleteAfter'
        /// </summary>
        [Fact]
        public void DeleteAfterTest()
        {
            // TODO unit test for the property 'DeleteAfter'
        }
    }
}
