/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing CheckUploadRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckUploadRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckUploadRequest
        //private CheckUploadRequest instance;

        public CheckUploadRequestTests()
        {
            // TODO uncomment below to create an instance of CheckUploadRequest
            //instance = new CheckUploadRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckUploadRequest
        /// </summary>
        [Fact]
        public void CheckUploadRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckUploadRequest
            //Assert.IsType<CheckUploadRequest>(instance);
        }

        /// <summary>
        /// Test the property 'FilesTitle'
        /// </summary>
        [Fact]
        public void FilesTitleTest()
        {
            // TODO unit test for the property 'FilesTitle'
        }
    }
}
