/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing CoEditingConfigMode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CoEditingConfigModeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CoEditingConfigMode
        //private CoEditingConfigMode instance;

        public CoEditingConfigModeTests()
        {
            // TODO uncomment below to create an instance of CoEditingConfigMode
            //instance = new CoEditingConfigMode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CoEditingConfigMode
        /// </summary>
        [Fact]
        public void CoEditingConfigModeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CoEditingConfigMode
            //Assert.IsType<CoEditingConfigMode>(instance);
        }
    }
}
