/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing CompanyWhiteLabelSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompanyWhiteLabelSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompanyWhiteLabelSettings
        //private CompanyWhiteLabelSettings instance;

        public CompanyWhiteLabelSettingsTests()
        {
            // TODO uncomment below to create an instance of CompanyWhiteLabelSettings
            //instance = new CompanyWhiteLabelSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompanyWhiteLabelSettings
        /// </summary>
        [Fact]
        public void CompanyWhiteLabelSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompanyWhiteLabelSettings
            //Assert.IsType<CompanyWhiteLabelSettings>(instance);
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Fact]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'IsLicensor'
        /// </summary>
        [Fact]
        public void IsLicensorTest()
        {
            // TODO unit test for the property 'IsLicensor'
        }
    }
}
