/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing CultureSpecificExternalResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CultureSpecificExternalResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CultureSpecificExternalResources
        //private CultureSpecificExternalResources instance;

        public CultureSpecificExternalResourcesTests()
        {
            // TODO uncomment below to create an instance of CultureSpecificExternalResources
            //instance = new CultureSpecificExternalResources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CultureSpecificExternalResources
        /// </summary>
        [Fact]
        public void CultureSpecificExternalResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CultureSpecificExternalResources
            //Assert.IsType<CultureSpecificExternalResources>(instance);
        }

        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Fact]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }

        /// <summary>
        /// Test the property 'Common'
        /// </summary>
        [Fact]
        public void CommonTest()
        {
            // TODO unit test for the property 'Common'
        }

        /// <summary>
        /// Test the property 'Forum'
        /// </summary>
        [Fact]
        public void ForumTest()
        {
            // TODO unit test for the property 'Forum'
        }

        /// <summary>
        /// Test the property 'Helpcenter'
        /// </summary>
        [Fact]
        public void HelpcenterTest()
        {
            // TODO unit test for the property 'Helpcenter'
        }

        /// <summary>
        /// Test the property 'Integrations'
        /// </summary>
        [Fact]
        public void IntegrationsTest()
        {
            // TODO unit test for the property 'Integrations'
        }

        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Fact]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }

        /// <summary>
        /// Test the property 'SocialNetworks'
        /// </summary>
        [Fact]
        public void SocialNetworksTest()
        {
            // TODO unit test for the property 'SocialNetworks'
        }

        /// <summary>
        /// Test the property 'Support'
        /// </summary>
        [Fact]
        public void SupportTest()
        {
            // TODO unit test for the property 'Support'
        }

        /// <summary>
        /// Test the property 'Videoguides'
        /// </summary>
        [Fact]
        public void VideoguidesTest()
        {
            // TODO unit test for the property 'Videoguides'
        }
    }
}
