/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing Culture
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CultureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Culture
        //private Culture instance;

        public CultureTests()
        {
            // TODO uncomment below to create an instance of Culture
            //instance = new Culture();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Culture
        /// </summary>
        [Fact]
        public void CultureInstanceTest()
        {
            // TODO uncomment below to test "IsType" Culture
            //Assert.IsType<Culture>(instance);
        }

        /// <summary>
        /// Test the property 'CultureName'
        /// </summary>
        [Fact]
        public void CultureNameTest()
        {
            // TODO unit test for the property 'CultureName'
        }
    }
}
