/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing DbTenant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DbTenantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DbTenant
        //private DbTenant instance;

        public DbTenantTests()
        {
            // TODO uncomment below to create an instance of DbTenant
            //instance = new DbTenant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DbTenant
        /// </summary>
        [Fact]
        public void DbTenantInstanceTest()
        {
            // TODO uncomment below to test "IsType" DbTenant
            //Assert.IsType<DbTenant>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }

        /// <summary>
        /// Test the property 'MappedDomain'
        /// </summary>
        [Fact]
        public void MappedDomainTest()
        {
            // TODO unit test for the property 'MappedDomain'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'VersionChanged'
        /// </summary>
        [Fact]
        public void VersionChangedTest()
        {
            // TODO unit test for the property 'VersionChanged'
        }

        /// <summary>
        /// Test the property 'VersionChanged'
        /// </summary>
        [Fact]
        public void VersionChangedTest()
        {
            // TODO unit test for the property 'VersionChanged'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'VarTimeZone'
        /// </summary>
        [Fact]
        public void VarTimeZoneTest()
        {
            // TODO unit test for the property 'VarTimeZone'
        }

        /// <summary>
        /// Test the property 'TrustedDomainsRaw'
        /// </summary>
        [Fact]
        public void TrustedDomainsRawTest()
        {
            // TODO unit test for the property 'TrustedDomainsRaw'
        }

        /// <summary>
        /// Test the property 'TrustedDomainsEnabled'
        /// </summary>
        [Fact]
        public void TrustedDomainsEnabledTest()
        {
            // TODO unit test for the property 'TrustedDomainsEnabled'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusChanged'
        /// </summary>
        [Fact]
        public void StatusChangedTest()
        {
            // TODO unit test for the property 'StatusChanged'
        }

        /// <summary>
        /// Test the property 'StatusChangedHack'
        /// </summary>
        [Fact]
        public void StatusChangedHackTest()
        {
            // TODO unit test for the property 'StatusChangedHack'
        }

        /// <summary>
        /// Test the property 'CreationDateTime'
        /// </summary>
        [Fact]
        public void CreationDateTimeTest()
        {
            // TODO unit test for the property 'CreationDateTime'
        }

        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Fact]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }

        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Fact]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }

        /// <summary>
        /// Test the property 'Calls'
        /// </summary>
        [Fact]
        public void CallsTest()
        {
            // TODO unit test for the property 'Calls'
        }

        /// <summary>
        /// Test the property 'Partner'
        /// </summary>
        [Fact]
        public void PartnerTest()
        {
            // TODO unit test for the property 'Partner'
        }
    }
}
