/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentConfigDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentConfigDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentConfigDto
        //private DocumentConfigDto instance;

        public DocumentConfigDtoTests()
        {
            // TODO uncomment below to create an instance of DocumentConfigDto
            //instance = new DocumentConfigDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentConfigDto
        /// </summary>
        [Fact]
        public void DocumentConfigDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentConfigDto
            //Assert.IsType<DocumentConfigDto>(instance);
        }

        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Fact]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }

        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

        /// <summary>
        /// Test the property 'IsLinkedForMe'
        /// </summary>
        [Fact]
        public void IsLinkedForMeTest()
        {
            // TODO unit test for the property 'IsLinkedForMe'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

        /// <summary>
        /// Test the property 'SharedLinkParam'
        /// </summary>
        [Fact]
        public void SharedLinkParamTest()
        {
            // TODO unit test for the property 'SharedLinkParam'
        }

        /// <summary>
        /// Test the property 'SharedLinkKey'
        /// </summary>
        [Fact]
        public void SharedLinkKeyTest()
        {
            // TODO unit test for the property 'SharedLinkKey'
        }

        /// <summary>
        /// Test the property 'ReferenceData'
        /// </summary>
        [Fact]
        public void ReferenceDataTest()
        {
            // TODO unit test for the property 'ReferenceData'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'IsForm'
        /// </summary>
        [Fact]
        public void IsFormTest()
        {
            // TODO unit test for the property 'IsForm'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
    }
}
