/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing DownloadRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DownloadRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DownloadRequestDto
        //private DownloadRequestDto instance;

        public DownloadRequestDtoTests()
        {
            // TODO uncomment below to create an instance of DownloadRequestDto
            //instance = new DownloadRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DownloadRequestDto
        /// </summary>
        [Fact]
        public void DownloadRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DownloadRequestDto
            //Assert.IsType<DownloadRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'FolderIds'
        /// </summary>
        [Fact]
        public void FolderIdsTest()
        {
            // TODO unit test for the property 'FolderIds'
        }

        /// <summary>
        /// Test the property 'FileIds'
        /// </summary>
        [Fact]
        public void FileIdsTest()
        {
            // TODO unit test for the property 'FileIds'
        }

        /// <summary>
        /// Test the property 'FileConvertIds'
        /// </summary>
        [Fact]
        public void FileConvertIdsTest()
        {
            // TODO unit test for the property 'FileConvertIds'
        }
    }
}
