/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing FileEntryType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileEntryTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileEntryType
        //private FileEntryType instance;

        public FileEntryTypeTests()
        {
            // TODO uncomment below to create an instance of FileEntryType
            //instance = new FileEntryType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileEntryType
        /// </summary>
        [Fact]
        public void FileEntryTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileEntryType
            //Assert.IsType<FileEntryType>(instance);
        }
    }
}
