/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing FileShareWrapper
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileShareWrapperTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileShareWrapper
        //private FileShareWrapper instance;

        public FileShareWrapperTests()
        {
            // TODO uncomment below to create an instance of FileShareWrapper
            //instance = new FileShareWrapper();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileShareWrapper
        /// </summary>
        [Fact]
        public void FileShareWrapperInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileShareWrapper
            //Assert.IsType<FileShareWrapper>(instance);
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
    }
}
