/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing GroupRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupRequestDto
        //private GroupRequestDto instance;

        public GroupRequestDtoTests()
        {
            // TODO uncomment below to create an instance of GroupRequestDto
            //instance = new GroupRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupRequestDto
        /// </summary>
        [Fact]
        public void GroupRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupRequestDto
            //Assert.IsType<GroupRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Fact]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }

        /// <summary>
        /// Test the property 'GroupManager'
        /// </summary>
        [Fact]
        public void GroupManagerTest()
        {
            // TODO unit test for the property 'GroupManager'
        }

        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
    }
}
