/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing InviteUsersRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InviteUsersRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InviteUsersRequestDto
        //private InviteUsersRequestDto instance;

        public InviteUsersRequestDtoTests()
        {
            // TODO uncomment below to create an instance of InviteUsersRequestDto
            //instance = new InviteUsersRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InviteUsersRequestDto
        /// </summary>
        [Fact]
        public void InviteUsersRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" InviteUsersRequestDto
            //Assert.IsType<InviteUsersRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Invitations'
        /// </summary>
        [Fact]
        public void InvitationsTest()
        {
            // TODO unit test for the property 'Invitations'
        }

        /// <summary>
        /// Test the property 'Culture'
        /// </summary>
        [Fact]
        public void CultureTest()
        {
            // TODO unit test for the property 'Culture'
        }
    }
}
