/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing IPRestrictionsSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IPRestrictionsSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IPRestrictionsSettings
        //private IPRestrictionsSettings instance;

        public IPRestrictionsSettingsTests()
        {
            // TODO uncomment below to create an instance of IPRestrictionsSettings
            //instance = new IPRestrictionsSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IPRestrictionsSettings
        /// </summary>
        [Fact]
        public void IPRestrictionsSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" IPRestrictionsSettings
            //Assert.IsType<IPRestrictionsSettings>(instance);
        }

        /// <summary>
        /// Test the property 'Enable'
        /// </summary>
        [Fact]
        public void EnableTest()
        {
            // TODO unit test for the property 'Enable'
        }
    }
}
