/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing NotificationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotificationType
        //private NotificationType instance;

        public NotificationTypeTests()
        {
            // TODO uncomment below to create an instance of NotificationType
            //instance = new NotificationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotificationType
        /// </summary>
        [Fact]
        public void NotificationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotificationType
            //Assert.IsType<NotificationType>(instance);
        }
    }
}
