/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing Operation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Operation
        //private Operation instance;

        public OperationTests()
        {
            // TODO uncomment below to create an instance of Operation
            //instance = new Operation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Operation
        /// </summary>
        [Fact]
        public void OperationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Operation
            //Assert.IsType<Operation>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Fact]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }

        /// <summary>
        /// Test the property 'ServiceUnit'
        /// </summary>
        [Fact]
        public void ServiceUnitTest()
        {
            // TODO unit test for the property 'ServiceUnit'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Credit'
        /// </summary>
        [Fact]
        public void CreditTest()
        {
            // TODO unit test for the property 'Credit'
        }

        /// <summary>
        /// Test the property 'Withdrawal'
        /// </summary>
        [Fact]
        public void WithdrawalTest()
        {
            // TODO unit test for the property 'Withdrawal'
        }
    }
}
