/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing OrderRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderRequestDto
        //private OrderRequestDto instance;

        public OrderRequestDtoTests()
        {
            // TODO uncomment below to create an instance of OrderRequestDto
            //instance = new OrderRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderRequestDto
        /// </summary>
        [Fact]
        public void OrderRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderRequestDto
            //Assert.IsType<OrderRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
