/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing OrdersItemRequestDtoInteger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrdersItemRequestDtoIntegerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrdersItemRequestDtoInteger
        //private OrdersItemRequestDtoInteger instance;

        public OrdersItemRequestDtoIntegerTests()
        {
            // TODO uncomment below to create an instance of OrdersItemRequestDtoInteger
            //instance = new OrdersItemRequestDtoInteger();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdersItemRequestDtoInteger
        /// </summary>
        [Fact]
        public void OrdersItemRequestDtoIntegerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrdersItemRequestDtoInteger
            //Assert.IsType<OrdersItemRequestDtoInteger>(instance);
        }

        /// <summary>
        /// Test the property 'EntryId'
        /// </summary>
        [Fact]
        public void EntryIdTest()
        {
            // TODO unit test for the property 'EntryId'
        }

        /// <summary>
        /// Test the property 'EntryType'
        /// </summary>
        [Fact]
        public void EntryTypeTest()
        {
            // TODO unit test for the property 'EntryType'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
