/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing PasswordSettingsRequestsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PasswordSettingsRequestsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PasswordSettingsRequestsDto
        //private PasswordSettingsRequestsDto instance;

        public PasswordSettingsRequestsDtoTests()
        {
            // TODO uncomment below to create an instance of PasswordSettingsRequestsDto
            //instance = new PasswordSettingsRequestsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PasswordSettingsRequestsDto
        /// </summary>
        [Fact]
        public void PasswordSettingsRequestsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PasswordSettingsRequestsDto
            //Assert.IsType<PasswordSettingsRequestsDto>(instance);
        }

        /// <summary>
        /// Test the property 'MinLength'
        /// </summary>
        [Fact]
        public void MinLengthTest()
        {
            // TODO unit test for the property 'MinLength'
        }

        /// <summary>
        /// Test the property 'UpperCase'
        /// </summary>
        [Fact]
        public void UpperCaseTest()
        {
            // TODO unit test for the property 'UpperCase'
        }

        /// <summary>
        /// Test the property 'Digits'
        /// </summary>
        [Fact]
        public void DigitsTest()
        {
            // TODO unit test for the property 'Digits'
        }

        /// <summary>
        /// Test the property 'SpecSymbols'
        /// </summary>
        [Fact]
        public void SpecSymbolsTest()
        {
            // TODO unit test for the property 'SpecSymbols'
        }
    }
}
