/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing PermissionsConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PermissionsConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PermissionsConfig
        //private PermissionsConfig instance;

        public PermissionsConfigTests()
        {
            // TODO uncomment below to create an instance of PermissionsConfig
            //instance = new PermissionsConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PermissionsConfig
        /// </summary>
        [Fact]
        public void PermissionsConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" PermissionsConfig
            //Assert.IsType<PermissionsConfig>(instance);
        }

        /// <summary>
        /// Test the property 'ChangeHistory'
        /// </summary>
        [Fact]
        public void ChangeHistoryTest()
        {
            // TODO unit test for the property 'ChangeHistory'
        }

        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }

        /// <summary>
        /// Test the property 'Chat'
        /// </summary>
        [Fact]
        public void ChatTest()
        {
            // TODO unit test for the property 'Chat'
        }

        /// <summary>
        /// Test the property 'Download'
        /// </summary>
        [Fact]
        public void DownloadTest()
        {
            // TODO unit test for the property 'Download'
        }

        /// <summary>
        /// Test the property 'Edit'
        /// </summary>
        [Fact]
        public void EditTest()
        {
            // TODO unit test for the property 'Edit'
        }

        /// <summary>
        /// Test the property 'FillForms'
        /// </summary>
        [Fact]
        public void FillFormsTest()
        {
            // TODO unit test for the property 'FillForms'
        }

        /// <summary>
        /// Test the property 'ModifyFilter'
        /// </summary>
        [Fact]
        public void ModifyFilterTest()
        {
            // TODO unit test for the property 'ModifyFilter'
        }

        /// <summary>
        /// Test the property 'Protect'
        /// </summary>
        [Fact]
        public void ProtectTest()
        {
            // TODO unit test for the property 'Protect'
        }

        /// <summary>
        /// Test the property 'Print'
        /// </summary>
        [Fact]
        public void PrintTest()
        {
            // TODO unit test for the property 'Print'
        }

        /// <summary>
        /// Test the property 'Rename'
        /// </summary>
        [Fact]
        public void RenameTest()
        {
            // TODO unit test for the property 'Rename'
        }

        /// <summary>
        /// Test the property 'Review'
        /// </summary>
        [Fact]
        public void ReviewTest()
        {
            // TODO unit test for the property 'Review'
        }

        /// <summary>
        /// Test the property 'Copy'
        /// </summary>
        [Fact]
        public void CopyTest()
        {
            // TODO unit test for the property 'Copy'
        }
    }
}
