/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing ProviderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProviderDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProviderDto
        //private ProviderDto instance;

        public ProviderDtoTests()
        {
            // TODO uncomment below to create an instance of ProviderDto
            //instance = new ProviderDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProviderDto
        /// </summary>
        [Fact]
        public void ProviderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProviderDto
            //Assert.IsType<ProviderDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Connected'
        /// </summary>
        [Fact]
        public void ConnectedTest()
        {
            // TODO unit test for the property 'Connected'
        }

        /// <summary>
        /// Test the property 'Oauth'
        /// </summary>
        [Fact]
        public void OauthTest()
        {
            // TODO unit test for the property 'Oauth'
        }

        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Fact]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }

        /// <summary>
        /// Test the property 'RequiredConnectionUrl'
        /// </summary>
        [Fact]
        public void RequiredConnectionUrlTest()
        {
            // TODO unit test for the property 'RequiredConnectionUrl'
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
    }
}
