/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing Run
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RunTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Run
        //private Run instance;

        public RunTests()
        {
            // TODO uncomment below to create an instance of Run
            //instance = new Run();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Run
        /// </summary>
        [Fact]
        public void RunInstanceTest()
        {
            // TODO uncomment below to test "IsType" Run
            //Assert.IsType<Run>(instance);
        }

        /// <summary>
        /// Test the property 'Fill'
        /// </summary>
        [Fact]
        public void FillTest()
        {
            // TODO unit test for the property 'Fill'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'FontSize'
        /// </summary>
        [Fact]
        public void FontSizeTest()
        {
            // TODO unit test for the property 'FontSize'
        }
    }
}
