/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing SchemaBaseRequestsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchemaBaseRequestsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchemaBaseRequestsDto
        //private SchemaBaseRequestsDto instance;

        public SchemaBaseRequestsDtoTests()
        {
            // TODO uncomment below to create an instance of SchemaBaseRequestsDto
            //instance = new SchemaBaseRequestsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchemaBaseRequestsDto
        /// </summary>
        [Fact]
        public void SchemaBaseRequestsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchemaBaseRequestsDto
            //Assert.IsType<SchemaBaseRequestsDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
