/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing StartFillingForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StartFillingFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StartFillingForm
        //private StartFillingForm instance;

        public StartFillingFormTests()
        {
            // TODO uncomment below to create an instance of StartFillingForm
            //instance = new StartFillingForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StartFillingForm
        /// </summary>
        [Fact]
        public void StartFillingFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" StartFillingForm
            //Assert.IsType<StartFillingForm>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
    }
}
