/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing StorageRequestsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StorageRequestsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StorageRequestsDto
        //private StorageRequestsDto instance;

        public StorageRequestsDtoTests()
        {
            // TODO uncomment below to create an instance of StorageRequestsDto
            //instance = new StorageRequestsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StorageRequestsDto
        /// </summary>
        [Fact]
        public void StorageRequestsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" StorageRequestsDto
            //Assert.IsType<StorageRequestsDto>(instance);
        }

        /// <summary>
        /// Test the property 'Module'
        /// </summary>
        [Fact]
        public void ModuleTest()
        {
            // TODO unit test for the property 'Module'
        }

        /// <summary>
        /// Test the property 'Props'
        /// </summary>
        [Fact]
        public void PropsTest()
        {
            // TODO unit test for the property 'Props'
        }
    }
}
