/*
 * ASC.Web.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing StorageFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StorageFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StorageFilter
        //private StorageFilter instance;

        public StorageFilterTests()
        {
            // TODO uncomment below to create an instance of StorageFilter
            //instance = new StorageFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StorageFilter
        /// </summary>
        [Fact]
        public void StorageFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" StorageFilter
            //Assert.IsType<StorageFilter>(instance);
        }
    }
}
