/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitForm
        //private SubmitForm instance;

        public SubmitFormTests()
        {
            // TODO uncomment below to create an instance of SubmitForm
            //instance = new SubmitForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitForm
        /// </summary>
        [Fact]
        public void SubmitFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitForm
            //Assert.IsType<SubmitForm>(instance);
        }

        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Fact]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }

        /// <summary>
        /// Test the property 'ResultMessage'
        /// </summary>
        [Fact]
        public void ResultMessageTest()
        {
            // TODO unit test for the property 'ResultMessage'
        }
    }
}
