/*
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Docspace.Model;
using Docspace.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Docspace.Test.Model
{
    /// <summary>
    ///  Class for testing ThirdPartyParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThirdPartyParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThirdPartyParams
        //private ThirdPartyParams instance;

        public ThirdPartyParamsTests()
        {
            // TODO uncomment below to create an instance of ThirdPartyParams
            //instance = new ThirdPartyParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThirdPartyParams
        /// </summary>
        [Fact]
        public void ThirdPartyParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThirdPartyParams
            //Assert.IsType<ThirdPartyParams>(instance);
        }

        /// <summary>
        /// Test the property 'AuthData'
        /// </summary>
        [Fact]
        public void AuthDataTest()
        {
            // TODO unit test for the property 'AuthData'
        }

        /// <summary>
        /// Test the property 'Corporate'
        /// </summary>
        [Fact]
        public void CorporateTest()
        {
            // TODO unit test for the property 'Corporate'
        }

        /// <summary>
        /// Test the property 'RoomsStorage'
        /// </summary>
        [Fact]
        public void RoomsStorageTest()
        {
            // TODO unit test for the property 'RoomsStorage'
        }

        /// <summary>
        /// Test the property 'CustomerTitle'
        /// </summary>
        [Fact]
        public void CustomerTitleTest()
        {
            // TODO unit test for the property 'CustomerTitle'
        }

        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }

        /// <summary>
        /// Test the property 'ProviderKey'
        /// </summary>
        [Fact]
        public void ProviderKeyTest()
        {
            // TODO unit test for the property 'ProviderKey'
        }
    }
}
